### ISSUE TITLE
N in the fastq files

### ISSUE THREAD

**Issue by ggnatalia** [ggnatalia/MMs#6]
Got one email in which a user was testing M&Ms. I'm copying my answer here in case it helps other users.

**QUESTION**
"""
  Something may be wrong with InSilicoSeqs, most of the reads are only “NNN” sequences. 
"""

**ANSWER**

"""
I know that it could be strange, but it is made on purpose. 

The reason was that when you recover reads from metagenomics, part of the read has no reason to belong to the 16S, but to other genes, we cover these cases with 'N'.

The number  of 'N' could be control using the '--_**ambiguities**_', default = 500. 

So, you can remove them if you want to. Besides, in the fastq file which groups the reads of all the samples together (xxx.allsamples.200000-perfect-150r-200i.fastq), these 'N' have been removed.
"""

**Comment by fpusan** [comment]
Acabo de darme cuenta de qe "-ambiguidities" está mal deletreado!

**Comment by ggnatalia** [comment]
Solved!
